// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// main_chromDraw
int main_chromDraw(int argc, StringVector argv);
RcppExport SEXP chromDraw_main_chromDraw(SEXP argcSEXP, SEXP argvSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type argc(argcSEXP );
        Rcpp::traits::input_parameter< StringVector >::type argv(argvSEXP );
        int __result = main_chromDraw(argc, argv);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
